# Generated by Django 3.1.6 on 2021-04-08 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_ceo', models.CharField(blank=True, max_length=20, null=True)),
                ('company_about', models.TextField(blank=True, max_length=500, null=True)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(upload_to='Employer/company_logos/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
