# Generated by Django 3.1.6 on 2021-02-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_employee',
            new_name='is_employer',
        ),
    ]
