# Generated by Django 3.1.6 on 2021-03-24 11:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0004_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
