# Generated by Django 3.1.6 on 2021-03-24 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfileApp', '0009_companydetail_company_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companydetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
